server:
    port: 9999
    servlet:
        context-path: /drools
spring:
    application:
        name: supplychain-encrypt
    messages:
        basename: i18n/messages 
    http:
        encoding:
         charset: UTF-8
         enabled: true
         force: true
auth:
    sso:
        anonPattern: /drools/**;